// GAME
export const INCREMENT_SCORE = 'INCREMENT_SCORE'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_PLACE = 'SET_PLACE'
// QUIZ
export const SET_QUIZ = 'SET_QUIZ'
export const SET_PROGRESS = 'SET_PROGRESS'
export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS'
export const START_TRANSITION = 'START_TRANSITION'
export const SHOW_TYPE_ERROR = 'SHOW_TYPE_ERROR'
export const SKIP_QUESTION = 'SKIP_QUESTION'
export const QUIZ_HAS_FINISHED = 'QUIZ_HAS_FINISHED'
export const SAVE_PROGRESSION = 'SAVE_PROGRESSION'
// WEBGL
export const WEBGL_ADD_GROUP = 'WEBGL_ADD_GROUP'
export const WEBGL_CLEAR_GROUP = 'WEBGL_CLEAR_GROUP'
