// GAME
export const INCREMENT_SCORE = 'INCREMENT_SCORE'
export const DECREMENT_SCORE = 'DECREMENT_SCORE'
export const SET_SCORE = 'SET_SCORE'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
// QUIZ
export const SET_QUIZ = 'SET_QUIZ'
export const SET_PROGRESS = 'SET_PROGRESS'
export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS'
export const SKIP_QUESTION = 'SKIP_QUESTION'
export const QUIZ_HAS_FINISHED = 'QUIZ_HAS_FINISHED'
// WEBGL
export const WEBGL_ADD_GROUP = 'WEBGL_ADD_GROUP'
export const WEBGL_CLEAR_GROUP = 'WEBGL_CLEAR_GROUP'
